replicaCount: 1

image:
  repository: openzipkin/zipkin
  pullPolicy: IfNotPresent
  tag: 2.23.16

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 9411

ingress:
  className: nginx
  path: /

resources:
  limits:
    cpu: 500m
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 128Mi

basicAuth:
  enable: true
  username: zipkin
  password: teRWANTE

zipkin:
  storage:
    type: mem # mem, cassandra3
    cassandra:
      host: cassandra-headless
      username: cassandra
      password: cassandra
