replicaCount: 1

image:
  repository: sonarqube
  tag: 9.4.0-community
  pullPolicy: IfNotPresent

securityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000

hostName: ''

sonarWebContext: /

service:
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /

startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 24
  sonarWebContext: /

initSysctl:
  enabled: true
  vmMaxMapCount: 524288
  fsFileMax: 131072
  nofile: 131072
  nproc: 8192
  securityContext:
    privileged: true

initFs:
  enabled: true
  securityContext:
    privileged: true

# List of plugins to install.
# For example:
# plugins:
#  install:
#    - "https://github.com/AmadeusITGroup/sonar-stash/releases/download/1.3.0/sonar-stash-plugin-1.3.0.jar"
#    - "https://github.com/SonarSource/sonar-ldap/releases/download/2.2-RC3/sonar-ldap-plugin-2.2.0.601.jar"
plugins:
  install: []
  lib: []
  noCheckCertificate: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

resources:
  limits:
    cpu: 800m
    memory: 2Gi
  requests:
    cpu: 400m
    memory: 1Gi

persistentStorage:
  enabled: false
  type: ebs
  hostPath: ""
  volumeID: ""

monitoringPasscode: "sona_change_this"

sonarqubeFolder: /opt/sonarqube

terminationGracePeriodSeconds: 60

nodeSelector: {}

postgresql:
  postgresql:
    database: "sonarDB"

  primary:
    dbUsername: "sonarUser"
    dbPassword: "sonarPassword"
