replicaCount: 1

image:
  repository: bitnami/postgresql
  pullPolicy: IfNotPresent
  tag: 14.2.0

imagePullSecrets: []

diagnosticMode:
  enabled: false

architecture: standalone # replication

replication:
  applicationName: offline_application
  replicationUsername: repl_user
  replicationPassword: password
  replicationCount: 1

postgresql:
  database: ""

primary:
  dbUsername: ""
  dbPassword: ""

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  securityContext:
    enabled: true
    runAsUser: 1001

  service:
    type: ClusterIP
    port: 5432

  resources:
    requests:
      cpu: 250m
      memory: 256Mi

persistentStorage:
  enable: false
  type: ebs
  hostPath: ""
  volumeID: ""

secondary:
  hostPath: ""

nodeSelector: {}
