enable:
  prometheus: true
  grafana: true
  nodeExporter: true
  kubeStateMetrics: true

prometheus:
  reverseProxy: false
  externalUrl: /prometheus
  routePrefix: /prometheus

  basicAuth:
    enable: false

grafana:
  reverseProxy: true
  rootUrl: '%(protocol)s://%(domain)s:%(http_port)s/grafana'

ingress:
  enable: true
