apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --save 60 100
            - --stop-writes-on-bgsave-error no
            - --rdbcompression yes
            - --dbfilename dump.rdb
            - --appendonly yes
            - --appendfsync no
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - /bin/sh
                - -c
                - /health/healthz.sh 5
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - /bin/sh
                - -c
                - /health/healthz.sh 1
          volumeMounts:
            - mountPath: /health
              name: health
            - mountPath: /data
              name: data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: health
          configMap:
            name: {{ include "redis.name" . }}-health
            defaultMode: 0755
        - name: data
          hostPath:
            path: {{ include "redis.data" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
