apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.name" . }}-health
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  healthz.sh: |-
    #!/bin/bash

    response=$(
      timeout -s 3 $1 \
      redis-cli \
        -h localhost \
        -p 6379 \
        ping
    )
    if [ "$?" -eq "124" ]; then
      echo "Timed out"
      exit 1
    fi
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
