apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.name" . }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: intra
      port: 7000
      targetPort: intra
    - name: cql
      port: {{ .Values.service.ports.cql }}
      targetPort: cql
  selector:
    {{- include "cassandra.selectorLabels" . | nindent 4 }}
