apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: cql
      port: {{ .Values.service.ports.cql }}
      targetPort: cql
      protocol: TCP
  selector:
    {{- include "cassandra.selectorLabels" . | nindent 4 }}
