{{- if .Values.enable.grafana }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        {{- if .Values.prometheus.reverseProxy }}
        url: http://prometheus-service:9090{{ .Values.prometheus.externalUrl }}
        {{- else }}
        url: http://prometheus-service:9090
        {{- end }}
        editable: true
        {{- if .Values.prometheus.basicAuth.enable }}
        basicAuth: true
        basicAuthUser: admin
        secureJsonData:
          basicAuthPassword: eignaUTE
        {{- end }}
{{- end }}
