{{- if .Values.enable.prometheus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus/config-map.yml") . | sha256sum }}
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.39.1
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus/"
          - "--web.enable-lifecycle"
          {{- if .Values.prometheus.reverseProxy }}
          - "--web.external-url={{ .Values.prometheus.externalUrl }}"
          - "--web.route-prefix={{ .Values.prometheus.routePrefix }}"
          {{- end }}
          {{- if .Values.prometheus.basicAuth.enable }}
          - "--web.config.file=/etc/prometheus/web.yml"
          {{- end }}
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/web.yml
          subPath: web.yml
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      serviceAccountName: prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: prometheus-server-conf
      - name: prometheus-storage-volume
        emptyDir: {}
{{- end }}
