apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.primary.name" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.primary.service.type }}
  ports:
    - name: tcp-postgresql
      port: {{ .Values.primary.service.port }}
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/role: master
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
