{{- if .Values.basicAuth.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zipkin.fullname" . }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile            on;
      keepalive_timeout   65;
      gzip                on;
      gzip_types          text/css application/json application/javascript text/javascript;

      server {
        listen      80;
        server_name localhost;
        root        /usr/share/nginx/html;
        index       index.html index.htm;

        location / {
          return 301 /zipkin;
        }

        location /zipkin {
          proxy_pass          http://localhost:{{ .Values.service.port }};
          proxy_set_header    Host $host;
          proxy_set_header    X-Real-IP $remote_addr;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_read_timeout  1800;
          proxy_connect_timeout 1800;
          auth_basic            "Restricted Content";
          auth_basic_user_file  /etc/nginx/.htpasswd;
        }

      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zipkin.fullname" . }}-htpasswd
data:
  .htpasswd: |
    {{ htpasswd .Values.basicAuth.username .Values.basicAuth.password }}

{{- end }}
