apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zipkin.fullname" . }}
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zipkin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zipkin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        {{- if .Values.basicAuth.enable }}
        - name: nginx
          image: nginx:1.22
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
            subPath: nginx.conf
          - mountPath: /etc/nginx/.htpasswd
            name: nginx-htpasswd
            subPath: .htpasswd
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STORAGE_TYPE
              value: {{ .Values.zipkin.storage.type | quote }}
            {{- if eq .Values.zipkin.storage.type "cassandra3" }}
            {{- with .Values.zipkin.storage.cassandra }}
            - name: CASSANDRA_CONTACT_POINTS
              value: {{ .host | quote }}
            - name: CASSANDRA_USERNAME
              value: {{ .username | quote }}
            - name: CASSANDRA_PASSWORD
              value: {{ .password | quote }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.basicAuth.enable }}
      volumes:
      - name: nginx-conf
        configMap:
          defaultMode: 420
          name: {{ include "zipkin.fullname" . }}
      - name: nginx-htpasswd
        configMap:
          defaultMode: 420
          name: {{ include "zipkin.fullname" . }}-htpasswd
      {{- end }}
