apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zipkin.fullname" . }}
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "zipkin.fullname" . }}
                port:
                  {{- if .Values.basicAuth.enable }}
                  number: 80
                  {{- else }}
                  number: {{ .Values.service.port }}
                  {{- end }}
