apiVersion: v1
kind: Service
metadata:
  name: {{ include "zipkin.fullname" . }}
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9411
      protocol: TCP
      name: http-query
    {{- if .Values.basicAuth.enable }}
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "zipkin.selectorLabels" . | nindent 4 }}
