apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.primary.dbPassword | b64enc }}
  {{- if eq .Values.architecture "replication" }}
  replication-password: {{ .Values.replication.replicationPassword | b64enc }}
  {{- end}}