apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ template "sonarqube.fullname" . }}
            port:
              number: 9000
        path: {{ .Values.sonarWebContext }}
        pathType: ImplementationSpecific
