apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "sonarqube.name" . }}
